In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay
)

In [4]:
iris = load_iris(as_frame=True)

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [7]:
dfIris = iris.frame
dfIris.head(2)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0

In [8]:
dfIris.tail(2)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [11]:
dfIris.rename(columns={"target" : "species"}, inplace=True)

In [12]:
dfIris["species"] = dfIris["species"].map(
    {
        0: "setosa",
        1: "versicolor",
        2: "virginica"
    }
)

In [13]:
dfIris.tail(5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

## Variables predictoras y variable objetivo 

X (Variables predictoras) son aquellas que me permiten hacer la prediccion 
Y (objetivo) Lo que quiero predecir

In [14]:
x = dfIris.drop(columns=["species"])

In [15]:
##variables objetivo
y = dfIris["species"]

In [16]:
print(" ---- Variables predictoras ---- ")
print(x.columns)
print(" ---- Variable Objetivo ----- ")
print(y.name)

 ---- Variables predictoras ----
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')
 ---- Variable Objetivo -----
species

## Division del conjuntos de datos

*Training set:* Datos para entrenamiento.
*Testing set:* Datos no vistos por el modelo, para prueba

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    x, 
    y,
    test_size = 0.20,
    random_state=42,
    stratify=y
)

In [19]:
print("X_train: ", X_train.shape)
print("X_test: ", X_test.shape)
print("--------------------------")
print("y_train: ", y_train.shape)
print("y_test: ", y_test.shape)

X_train:  (120, 4)
X_test:  (30, 4)
--------------------------
y_train:  (120,)
y_test:  (30,)

In [20]:
scaler = StandardScaler()

In [21]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
print("-----Datos sin escalar-------- ")
print(X_train)
 
print("-------Escalados--------- ")   
print(X_train_scaled)

-----Datos sin escalar--------
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                  4.4               2.9                1.4               0.2
106                4.9               2.5                4.5               1.7
76                 6.8               2.8                4.8               1.4
9                  4.9               3.1                1.5               0.1
89                 5.5               2.5                4.0               1.3
..                 ...               ...                ...               ...
37                 4.9               3.6                1.4               0.1
2                  4.7               3.2                1.3               0.2
33                 5.5               4.2                1.4               0.2
52                 6.9               3.1                4.9               1.5
3                  4.6               3.1                1.5               0.2

[120 rows x 4 columns]
-------Escalados---------
[[-1.72156775 -0.33210111 -1.34572231 -1.32327558]
 [-1.12449223 -1.22765467  0.41450518  0.6517626 ]
 [ 1.14439475 -0.5559895   0.58484978  0.25675496]
 [-1.12449223  0.11567567 -1.28894078 -1.45494479]
 [-0.40800161 -1.22765467  0.13059752  0.12508575]
 [ 0.54731923 -1.22765467  0.69841284  0.91510102]
 [-0.2885865  -0.77987789  0.24416059  0.12508575]
 [ 0.54731923 -0.5559895   0.75519438  0.38842418]
 [ 2.21913069 -0.10821272  1.3230097   1.44177787]
 [ 2.21913069  1.6828944   1.66369889  1.31010866]
 [ 2.09971558 -0.10821272  1.60691736  1.17843945]
 [ 0.18907392 -0.33210111  0.41450518  0.38842418]
 [-1.00507713 -2.34709662 -0.15331014 -0.26992188]
 [-0.04975629 -0.77987789  0.18737906 -0.26992188]
 [-0.04975629 -1.00376628  0.13059752 -0.00658346]
 [-1.36332244  0.33956406 -1.23215924 -1.32327558]
 [-0.88566202  1.6828944  -1.28894078 -1.19160637]
 [ 1.02497964 -1.22765467  1.1526651   0.78343181]
 [ 0.66673433  0.11567567  0.9823205   0.78343181]
 [-0.52741671  0.78734084 -1.28894078 -1.05993716]
 [ 0.54731923 -1.22765467  0.64163131  0.38842418]
 [-0.88566202  1.6828944  -1.23215924 -1.32327558]
 [ 2.4579609   1.6828944   1.49335429  1.04677024]
 [-1.00507713 -0.10821272 -1.23215924 -1.32327558]
 [-0.40800161 -1.45154306 -0.03974707 -0.26992188]
 [ 0.54731923 -0.33210111  1.03910204  0.78343181]
 [ 0.66673433 -0.77987789  0.86875744  0.91510102]
 [-1.00507713  0.78734084 -1.23215924 -1.05993716]
 [-0.2885865  -0.5559895   0.64163131  1.04677024]
 [-1.00507713  1.01122923 -1.40250384 -1.19160637]
 [-0.88566202  1.45900601 -1.28894078 -1.05993716]
 [ 0.30848902 -0.5559895   0.13059752  0.12508575]
 [ 0.30848902 -0.10821272  0.47128672  0.25675496]
 [-0.1691714   3.02622474 -1.28894078 -1.05993716]
 [ 1.26380985  0.11567567  0.92553897  1.17843945]
 [ 0.42790412  0.78734084  0.92553897  1.44177787]
 [-0.1691714  -1.00376628 -0.15331014 -0.26992188]
 [-0.76624692 -0.77987789  0.07381599  0.25675496]
 [ 1.02497964  0.56345245  1.09588357  1.7051163 ]
 [ 0.06965881  0.33956406  0.58484978  0.78343181]
 [-1.48273754  0.78734084 -1.34572231 -1.19160637]
 [ 1.38322496  0.33956406  0.52806825  0.25675496]
 [-0.52741671  1.90678279 -1.40250384 -1.05993716]
 [ 1.86088537 -0.5559895   1.3230097   0.91510102]
 [-1.12449223 -0.10821272 -1.34572231 -1.32327558]
 [-0.88566202  1.01122923 -1.34572231 -1.19160637]
 [-0.04975629 -0.77987789  0.75519438  0.91510102]
 [-1.00507713  0.33956406 -1.45928537 -1.32327558]
 [-1.60215265 -1.67543145 -1.40250384 -1.19160637]
 [-1.24390734 -0.10821272 -1.34572231 -1.45494479]
 [-1.24390734 -0.10821272 -1.34572231 -1.19160637]
 [-0.2885865  -0.33210111 -0.0965286   0.12508575]
 [ 0.54731923  0.56345245  1.26622816  1.7051163 ]
 [-0.1691714  -0.5559895   0.41450518  0.12508575]
 [-0.88566202  1.01122923 -1.34572231 -1.32327558]
 [ 0.06965881 -0.10821272  0.75519438  0.78343181]
 [-0.1691714  -0.5559895   0.18737906  0.12508575]
 [ 0.54731923  0.78734084  1.03910204  1.57344709]
 [-1.48273754  0.33956406 -1.34572231 -1.32327558]
 [-0.04975629 -0.77987789  0.75519438  0.91510102]
 [-0.40800161  1.01122923 -1.40250384 -1.32327558]
 [-0.40800161 -1.67543145  0.13059752  0.12508575]
 [-0.1691714  -1.22765467  0.69841284  1.04677024]
 [-1.24390734  0.78734084 -1.06181465 -1.32327558]
 [ 0.18907392 -0.77987789  0.75519438  0.52009339]
 [-0.40800161 -1.00376628  0.35772365 -0.00658346]
 [ 2.21913069 -0.5559895   1.66369889  1.04677024]
 [-0.2885865  -0.10821272  0.41450518  0.38842418]
 [ 0.78614944 -0.5559895   0.47128672  0.38842418]
 [ 0.66673433  0.33956406  0.86875744  1.44177787]
 [-0.88566202  0.78734084 -1.28894078 -1.32327558]
 [-0.88566202  0.56345245 -1.17537771 -0.92826795]
 [-1.00507713  1.23511762 -1.34572231 -1.32327558]
 [ 0.18907392 -1.89931984  0.69841284  0.38842418]
 [-0.04975629 -0.77987789  0.07381599 -0.00658346]
 [ 1.62205517 -0.10821272  1.1526651   0.52009339]
 [-0.40800161 -1.45154306  0.01703446 -0.13825267]
 [ 1.02497964 -0.10821272  0.81197591  1.44177787]
 [ 0.54731923 -0.77987789  0.64163131  0.78343181]
 [ 0.18907392  0.78734084  0.41450518  0.52009339]
 [-1.12449223  0.11567567 -1.28894078 -1.32327558]
 [-0.04975629 -0.5559895   0.75519438  1.57344709]
 [ 0.42790412 -1.89931984  0.41450518  0.38842418]
 [-1.00507713  1.01122923 -1.23215924 -0.79659873]
 [ 1.26380985  0.33956406  1.09588357  1.44177787]
 [-0.76624692  2.35455957 -1.28894078 -1.45494479]
 [ 1.62205517  1.23511762  1.3230097   1.7051163 ]
 [-0.88566202 -1.22765467 -0.4372178  -0.13825267]
 [ 1.02497964  0.11567567  0.52806825  0.38842418]
 [-1.24390734  0.11567567 -1.23215924 -1.32327558]
 [ 0.42790412 -0.33210111  0.30094212  0.12508575]
 [ 0.78614944  0.33956406  0.75519438  1.04677024]
 [-0.88566202  1.6828944  -1.06181465 -1.05993716]
 [-1.84098286 -0.10821272 -1.5160669  -1.45494479]
 [ 1.02497964  0.56345245  1.09588357  1.17843945]
 [ 2.21913069 -1.00376628  1.77726195  1.44177787]
 [ 1.14439475 -0.10821272  0.9823205   1.17843945]
 [ 0.54731923 -1.67543145  0.35772365  0.12508575]
 [ 0.42790412 -0.5559895   0.58484978  0.78343181]
 [-0.52741671  1.90678279 -1.17537771 -1.05993716]
 [ 1.14439475  0.33956406  1.20944663  1.44177787]
 [-0.1691714  -0.33210111  0.24416059  0.12508575]
 [ 1.62205517  0.33956406  1.26622816  0.78343181]
 [ 1.50264006 -0.10821272  1.20944663  1.17843945]
 [-0.64683181  1.45900601 -1.28894078 -1.32327558]
 [ 0.66673433 -0.33210111  0.30094212  0.12508575]
 [ 0.30848902 -0.5559895   0.52806825 -0.00658346]
 [-0.1691714  -0.10821272  0.24416059 -0.00658346]
 [-0.2885865  -0.10821272  0.18737906  0.12508575]
 [ 1.02497964  0.11567567  0.35772365  0.25675496]
 [-0.76624692  1.01122923 -1.28894078 -1.32327558]
 [ 0.66673433 -0.5559895   1.03910204  1.17843945]
 [ 0.18907392 -1.89931984  0.13059752 -0.26992188]
 [ 0.06965881 -0.10821272  0.24416059  0.38842418]
 [-1.24390734  0.78734084 -1.23215924 -1.32327558]
 [-1.12449223  1.23511762 -1.34572231 -1.45494479]
 [-1.36332244  0.33956406 -1.40250384 -1.32327558]
 [-0.40800161  2.57844796 -1.34572231 -1.32327558]
 [ 1.26380985  0.11567567  0.64163131  0.38842418]
 [-1.48273754  0.11567567 -1.28894078 -1.32327558]]

In [25]:
print("-----------Datos sin escalar------------")
print(X_train.head(5))
print("-----------Escalados-----------")
print(X_train_scaled[:5])

-----------Datos sin escalar------------
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                  4.4               2.9                1.4               0.2
106                4.9               2.5                4.5               1.7
76                 6.8               2.8                4.8               1.4
9                  4.9               3.1                1.5               0.1
89                 5.5               2.5                4.0               1.3
-----------Escalados-----------
[[-1.72156775 -0.33210111 -1.34572231 -1.32327558]
 [-1.12449223 -1.22765467  0.41450518  0.6517626 ]
 [ 1.14439475 -0.5559895   0.58484978  0.25675496]
 [-1.12449223  0.11567567 -1.28894078 -1.45494479]
 [-0.40800161 -1.22765467  0.13059752  0.12508575]]

In [30]:
modelo = KNeighborsClassifier(
    n_neighbors = 3
)

In [31]:
modelo.fit (
    X_train_scaled,
    y_train
)

KNeighborsClassifier(n_neighbors=3)

In [32]:
prediccion = modelo.predict(X_test_scaled)

In [34]:
pd.DataFrame({
    "Especie real" : y_test.values,
    "Especie Predicha" : prediccion
}).head(20)

   Especie real Especie Predicha
0        setosa           setosa
1     virginica        virginica
2    versicolor       versicolor
3    versicolor       versicolor
4        setosa           setosa
5    versicolor       versicolor
6        setosa           setosa
7        setosa           setosa
8     virginica        virginica
9    versicolor       versicolor
10    virginica        virginica
11    virginica        virginica
12    virginica        virginica
13   versicolor       versicolor
14       setosa           setosa
15       setosa           setosa
16       setosa           setosa
17   versicolor       versicolor
18   versicolor       versicolor
19    virginica       versicolor